version: '2'

services:

  angular:
    build: .
    image: hotblac/spanners-angular:latest
    ports:
      - "8081:80"
    external_links:
      - api:spanners-api
    networks:
      - spanners-services
    restart: always

networks:
  # Connect to network provided by the main spanners project which includes the spanners-api
  spanners-services:
    external:
      name: spanners_default
